# Generated by Django 4.1.7 on 2023-03-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("update_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="update_db",
            name="Images",
            field=models.ImageField(blank=True, null=True, upload_to="profile"),
        ),
    ]
